version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3

workflows:
  version: 2
  build:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - main
      - publish:
          filters:
            branches:
              only:
                - main
          requires: 
            - build_and_test
      - deploy:
          filters:
            branches:
              only:
                - main
          requires: 
            - publish
jobs:
  build_and_test:
    working_directory: ~/app
    docker:
      - image: cimg/node:18.10-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install                     
      - restore_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: ng build
          command: npm run build --if-present
      - run: npm test -- --watch=false --browsers=ChromeHeadless
  publish:
    working_directory: ~/app
    docker:
      - image: cimg/node:18.10
    steps:
      - checkout
      - setup_remote_docker     
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: build-docker-image
          command: docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - run:
          name: publish-docker-image
          command: docker push $IMAGE_NAME:$IMAGE_TAG                    
  deploy:
    docker:
      - image: cimg/node:18.10
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export CONTAINER_NAME=\"$CONTAINER_NAME\";export IMAGE_NAME=\"$IMAGE_NAME\";export IMAGE_TAG=\"$IMAGE_TAG\";export PUBLIC_PORT=\"$PUBLIC_PORT\";export INTERNAL_PORT=\"$INTERNAL_PORT\";export SERVER=\"$SERVER\";export PRIVATE_KEY=\"$PRIVATE_KEY\";rm -rf MH-AIaaS-UI;git clone https://github.com/herreramaxi/MH-AIaaS-UI.git;source DevApp/deploy.sh"